name: Push

on:
  workflow_dispatch:
permissions:
  contents: write         # needed for fetching code
  packages: write    
  id-token: write


jobs:
  build:
    runs-on: kind
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install buildctl
        run: |
          curl -sSL https://github.com/moby/buildkit/releases/download/v0.12.5/buildkit-v0.12.5.linux-amd64.tar.gz | tar -xz
          sudo mv bin/buildctl /usr/local/bin/
      - name: DumpEnv
        run: env
      - name: Build image using BuildKit
        run: |
          buildctl \
            --addr tcp://buildkitd.arc-runners.svc.cluster.local:1234 \
            build \
            --frontend=dockerfile.v0 \
            --local context=. \
            --local dockerfile=. \
            --output type=image,name=ghcr.io/scav/actions-lab/buildkit:latest,push=true
