name: Run tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: kind
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - name: Run tests
        run: go test -v ./...
        env:
          CGO_ENABLED: 0
